### ISSUE TITLE
InaccessibleObjectException when using com.pixelduke.fxthemes with JavaFX or 

### ISSUE THREAD

**Issue by kinsleykajiva** [dukke/FXThemes#5] opened 2024-07-09 14:57 UTC
This error occurs in the WindowUtils class when trying to access the getPeer() method of the Window class.

```java

java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.javafx.tk.TKStage javafx.stage.Window.getPeer() accessible: module javafx.graphics does not "opens javafx.stage" to module com.pixelduke.fxthemes
```

The error is related to the accessibility of the getPeer() method in the Window class. The module javafx.graphics does not open the javafx.stage package to the module com.pixelduke.fxthemes, causing the error.

**Comment by dukke** [comment] 2024-07-09 18:43
Hi Kinsley,

This is not a bug. It's working as expected.

It's the other way around. You need to forcefully open javafx.graphics to com.pixelduke.fxthemes.

Please check the documentation: https://www.pixelduke.com/fxthemes/ and more specifically the final paragraph. You can also check the sample subproject to see a working example.

I'm closing this as this is not an issue.

Thanks! :)

**Closed as completed by dukke** 2024-07-09 18:43 UTC
